# Generated by Django 4.2.5 on 2023-12-27 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='auction.brand'),
        ),
    ]
