# Generated by Django 4.2.5 on 2023-12-27 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_listing_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='title',
            new_name='name',
        ),
    ]
