# Generated by Django 4.2.5 on 2023-12-28 11:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_listing_isexpired_alter_listing_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
