# Generated by Django 4.2.5 on 2023-12-28 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_alter_listing_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 29, 12, 22, 20, 548249, tzinfo=datetime.timezone.utc)),
        ),
    ]
