# Generated by Django 4.2.5 on 2023-12-28 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_alter_bid_user_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 29, 12, 41, 19, 911199, tzinfo=datetime.timezone.utc)),
        ),
    ]
