# Generated by Django 4.2.5 on 2023-12-28 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0017_user_picture_alter_listing_end_time_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='picture',
        ),
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 29, 16, 39, 7, 5346, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
