# Generated by Django 4.2.5 on 2023-12-28 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0018_remove_user_picture_alter_listing_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 29, 17, 38, 14, 111486, tzinfo=datetime.timezone.utc)),
        ),
    ]
