# Generated by Django 4.2.5 on 2024-01-12 02:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0023_alter_listing_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 2, 33, 10, 881118, tzinfo=datetime.timezone.utc)),
        ),
    ]
