# Generated by Django 4.2.5 on 2024-01-12 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0025_alter_listing_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='DefaultName', max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 10, 0, 5, 692757, tzinfo=datetime.timezone.utc)),
        ),
    ]
