# Generated by Django 4.2.5 on 2024-01-12 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0030_alter_listing_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 11, 37, 58, 256479, tzinfo=datetime.timezone.utc)),
        ),
    ]
