# Generated by Django 4.2.5 on 2024-01-14 13:55

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0033_remove_user_name_user_firstname_user_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobileNo',
            field=models.CharField(blank=True, help_text='Enter your 10-digit mobile number', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 15, 13, 55, 20, 418175, tzinfo=datetime.timezone.utc)),
        ),
    ]
