# Generated by Django 4.2.5 on 2024-01-14 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0034_user_mobileno_alter_listing_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, help_text='Enter your address', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 15, 13, 59, 40, 866152, tzinfo=datetime.timezone.utc)),
        ),
    ]
