# Generated by Django 5.0.2 on 2024-07-02 01:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0036_user_name_alter_listing_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 3, 1, 32, 28, 264978, tzinfo=datetime.timezone.utc)),
        ),
    ]
