# Generated by Django 5.0.2 on 2024-07-02 02:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0037_alter_listing_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='cylinders',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 3, 2, 41, 54, 759892, tzinfo=datetime.timezone.utc)),
        ),
    ]
