# Generated by Django 5.0.2 on 2024-07-02 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0042_listing_displacement_listing_power_listing_torque_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='description',
            new_name='summary',
        ),
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 3, 14, 26, 33, 561415, tzinfo=datetime.timezone.utc)),
        ),
    ]
