# Generated by Django 5.0.2 on 2024-07-02 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0043_rename_description_listing_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='fuel_tank_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='mileage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 3, 14, 38, 42, 999128, tzinfo=datetime.timezone.utc)),
        ),
    ]
