# Generated by Django 5.0.2 on 2024-07-02 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0044_listing_fuel_tank_capacity_listing_mileage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='top_speed',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 3, 16, 2, 21, 436265, tzinfo=datetime.timezone.utc)),
        ),
    ]
