# Generated by Django 5.0.2 on 2024-07-02 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0045_listing_top_speed_alter_listing_end_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='imageurl',
            new_name='image_url',
        ),
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 3, 16, 4, 52, 655897, tzinfo=datetime.timezone.utc)),
        ),
    ]
