# Generated by Django 5.0.2 on 2024-07-02 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0046_rename_imageurl_listing_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 3, 16, 34, 40, 131742, tzinfo=datetime.timezone.utc)),
        ),
    ]
