# Generated by Django 5.0.2 on 2024-07-02 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0048_listing_created_at_alter_listing_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 3, 18, 43, 53, 758834, tzinfo=datetime.timezone.utc)),
        ),
    ]
