# Generated by Django 5.0.2 on 2024-07-02 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0051_comment_comment_user_pic_alter_listing_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_user_pic',
        ),
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 3, 23, 21, 50, 255195, tzinfo=datetime.timezone.utc)),
        ),
    ]
