# Generated by Django 5.0.2 on 2024-07-06 01:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0053_alter_listing_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 7, 1, 14, 34, 482864, tzinfo=datetime.timezone.utc)),
        ),
    ]
