# Generated by Django 5.0.2 on 2024-07-07 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0060_alter_listing_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 7, 21, 47, 22, 428506, tzinfo=datetime.timezone.utc)),
        ),
    ]
