# Generated by Django 5.0.2 on 2024-07-07 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0062_alter_listing_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 8, 0, 55, 37, 408803, tzinfo=datetime.timezone.utc)),
        ),
    ]
