# Generated by Django 5.0.2 on 2024-07-08 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0067_alter_bid_bid_alter_listing_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 8, 18, 45, 54, 248459, tzinfo=datetime.timezone.utc)),
        ),
    ]
