# Generated by Django 5.0.2 on 2024-07-08 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0069_listing_collections_alter_listing_bid_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='collections',
        ),
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 8, 21, 6, 37, 221811, tzinfo=datetime.timezone.utc)),
        ),
    ]
