# Generated by Django 5.0.2 on 2024-07-08 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0071_listing_collections_alter_listing_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 8, 21, 57, 30, 387461, tzinfo=datetime.timezone.utc)),
        ),
    ]
