# Generated by Django 5.0.2 on 2024-07-08 21:22

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0072_alter_listing_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='collections',
        ),
        migrations.AddField(
            model_name='listing',
            name='collection',
            field=models.ManyToManyField(blank=True, related_name='collection', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 8, 22, 22, 38, 235144, tzinfo=datetime.timezone.utc)),
        ),
    ]
