# Generated by Django 5.0.2 on 2024-07-08 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0073_remove_listing_collections_listing_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 8, 22, 22, 44, 386636, tzinfo=datetime.timezone.utc)),
        ),
    ]
