# Generated by Django 5.0.2 on 2024-07-09 00:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0086_alter_bid_listing_alter_listing_end_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid',
            new_name='bid_amount',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='timestamp',
            new_name='bid_time',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='user',
            new_name='bidder',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='price',
            new_name='start_price',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='listing',
        ),
        migrations.AddField(
            model_name='listing',
            name='current_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auction.bid'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 9, 1, 54, 14, 101879, tzinfo=datetime.timezone.utc)),
        ),
    ]
