# Generated by Django 5.0.2 on 2024-07-09 00:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0087_rename_bid_bid_bid_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 9, 1, 54, 47, 72144, tzinfo=datetime.timezone.utc)),
        ),
    ]
