# Generated by Django 5.0.2 on 2024-07-09 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0098_alter_listing_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 9, 14, 46, 16, 384192, tzinfo=datetime.timezone.utc)),
        ),
    ]
