# Generated by Django 5.0.2 on 2024-07-10 22:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0115_remove_listing_current_bid_bid_listing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 10, 22, 20, 4, 149372, tzinfo=datetime.timezone.utc)),
        ),
    ]
