# Generated by Django 5.0.2 on 2024-07-12 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0118_alter_listing_end_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='fuel_tank_capacity',
            new_name='fuel_capacity',
        ),
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 5, 2, 54, 611543, tzinfo=datetime.timezone.utc)),
        ),
    ]
