# Generated by Django 5.0.2 on 2024-07-12 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0119_rename_fuel_tank_capacity_listing_fuel_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 20, 15, 11, 518658, tzinfo=datetime.timezone.utc)),
        ),
    ]
