# Generated by Django 5.0.2 on 2024-07-12 21:01

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0120_alter_listing_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='brandName',
        ),
        migrations.RemoveField(
            model_name='category',
            name='categoryName',
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_price', models.IntegerField(default=0)),
                ('cylinders', models.IntegerField(default=4)),
                ('displacement', models.FloatField(default=0)),
                ('power', models.FloatField(default=0)),
                ('torque', models.FloatField(default=0)),
                ('mileage', models.FloatField(default=0)),
                ('top_speed', models.IntegerField(default=0)),
                ('fuel_capacity', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Used', 'Used'), ('Restored', 'Restored'), ('Salvage', 'Salvage')], max_length=20)),
                ('price_range', models.CharField(choices=[('Budget', 'Up to $5,000'), ('Mid-Range', '$5,001 - $10,000'), ('Premium', '$10,001 - $20,000'), ('Luxury', 'Over $20,000')], max_length=20)),
                ('image_url', models.CharField(max_length=1000)),
                ('summary', models.CharField(max_length=1000)),
                ('isActive', models.BooleanField(default=True)),
                ('isExpired', models.BooleanField(default=False)),
                ('sold', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('end_time', models.DateTimeField(default=datetime.datetime(2024, 7, 12, 21, 11, 33, 375201, tzinfo=datetime.timezone.utc))),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='auction.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='auction.category')),
                ('collection', models.ManyToManyField(blank=True, related_name='collection', to=settings.AUTH_USER_MODEL)),
                ('engine_capacity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auction.enginecapacity')),
                ('features', models.ManyToManyField(blank=True, to='auction.feature')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('watchlist', models.ManyToManyField(blank=True, related_name='listingWatchList', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='motorcycle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.motorcycle'),
        ),
        migrations.AddField(
            model_name='comment',
            name='motorcycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listingComment', to='auction.motorcycle'),
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
