# Generated by Django 5.0.2 on 2024-07-12 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0121_enginecapacity_feature_remove_comment_listing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='engine_capacity',
            field=models.FloatField(default=0),
        ),
        migrations.RemoveField(
            model_name='motorcycle',
            name='displacement',
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 21, 23, 43, 61379, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='EngineCapacity',
        ),
    ]
