# Generated by Django 5.0.2 on 2024-07-12 21:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0122_alter_motorcycle_engine_capacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 12, 22, 8, 31, 120794, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='engine_capacity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auction.enginecapacity'),
        ),
    ]
