# Generated by Django 5.0.2 on 2024-07-17 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0137_alter_motorcycle_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 17, 4, 45, 33, 610092, tzinfo=datetime.timezone.utc)),
        ),
    ]
