# Generated by Django 5.0.2 on 2024-07-18 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0138_alter_motorcycle_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 18, 5, 34, 28, 276480, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='fuel_capacity',
            field=models.FloatField(default=0),
        ),
    ]
