# Generated by Django 5.0.2 on 2024-07-23 01:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0139_alter_motorcycle_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 23, 2, 24, 51, 369753, tzinfo=datetime.timezone.utc)),
        ),
    ]
