# Generated by Django 5.0.2 on 2024-07-23 01:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0140_alter_motorcycle_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 23, 2, 38, 56, 641650, tzinfo=datetime.timezone.utc)),
        ),
    ]
