# Generated by Django 5.0.2 on 2024-07-23 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0141_alter_motorcycle_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Black', 'Black'), ('White', 'White'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Silver', 'Silver'), ('Grey', 'Grey'), ('Orange', 'Orange'), ('Purple', 'Purple')], max_length=100),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 23, 21, 0, 5, 21055, tzinfo=datetime.timezone.utc)),
        ),
    ]
