# Generated by Django 5.0.2 on 2024-07-23 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0143_remove_motorcycle_price_range_alter_motorcycle_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 23, 21, 14, 53, 323828, tzinfo=datetime.timezone.utc)),
        ),
    ]
