# Generated by Django 5.0.2 on 2024-11-14 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0144_alter_motorcycle_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 14, 12, 35, 13, 382633, tzinfo=datetime.timezone.utc)),
        ),
    ]
