# Generated by Django 5.1.3 on 2024-11-14 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0145_alter_motorcycle_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 14, 12, 50, 42, 530251, tzinfo=datetime.timezone.utc)),
        ),
    ]
